apiVersion: v1
kind: Service
metadata:
  name: qoe-predictor
  namespace: ricxapp
  labels:
    app: qoe-predictor
    xapp: qoe-predictor
spec:
  type: ClusterIP
  selector:
    app: qoe-predictor
  ports:
  - name: rmr-data
    port: 4570
    targetPort: 4570
    protocol: TCP
  - name: rmr-route
    port: 4571
    targetPort: 4571
    protocol: TCP
  - name: http-api
    port: 8090
    targetPort: 8090
    protocol: TCP
