apiVersion: v1
kind: Service
metadata:
  name: kpimon
  namespace: ricxapp
  labels:
    app: kpimon
    xapp: kpimon
spec:
  type: ClusterIP
  selector:
    app: kpimon
  ports:
  - name: rmr-data
    port: 4560
    targetPort: 4560
    protocol: TCP
  - name: http-metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
