apiVersion: v1
kind: Service
metadata:
  name: traffic-steering
  namespace: ricxapp
  labels:
    app: traffic-steering
    xapp: traffic-steering
spec:
  type: ClusterIP
  ports:
  - name: rmr-data
    port: 4560
    targetPort: 4560
    protocol: TCP
  - name: rmr-route
    port: 4561
    targetPort: 4561
    protocol: TCP
  - name: http-api
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: traffic-steering
