apiVersion: v1
kind: Service
metadata:
  name: ran-control
  namespace: ricxapp
  labels:
    app: ran-control
    xapp: ran-control
spec:
  type: ClusterIP
  selector:
    app: ran-control
  ports:
  - name: rmr-data
    port: 4580
    targetPort: 4580
    protocol: TCP
  - name: rmr-route
    port: 4581
    targetPort: 4581
    protocol: TCP
  - name: http-api
    port: 8100
    targetPort: 8100
    protocol: TCP
